---
# tasks file for roles/manage_ssh_keys
- name: Ensure local ssh directory
  file:
    path: "{{ SSH_DIR }}"
    state: directory

- name: Ensure local save directory
  file:
    path: "{{ CREDENT_DIR }}"
    state: directory

# Launch tasks in a loop of users
- name: Start Loop tasks on users list
  include_tasks: loop.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: user_item