# ansible-playbook plays/install_zabbix_agent.yml -i inventories/freemind
# Probleme avec les machines PulseHeberg
---
- name: Install Zabbix Agents
  hosts: all
  remote_user: ansible
  become: yes
  
  roles:
#    - roles/
  
  vars:
    - ansible_become_password: ansible*/
    - zbx_srv: 217.182.165.158
    - debian9_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+stretch_all.deb
    - debian9_file: zabbix-release_4.4-1+stretch_all.deb
    - debian10_link: https://repo.zabbix.com/zabbix/4.4/debian/pool/main/z/zabbix-release/zabbix-release_4.4-1+buster_all.deb
    - debian10_file: zabbix-release_4.4-1+buster_all.deb
  
  pre_tasks:

  tasks:
    ##### Install zabbix-agent
    - name: ping hosts
      ping:

    - name: check OS
      debug: msg={{ansible_distribution}}-{{ansible_distribution_version}}

    # Debian 9
    - name: download zabbix deb file for Debian 9
      get_url:
        url: "{{ debian9_link }}"
        dest: "/tmp/{{ debian9_file }}"
      when: ansible_distribution_release == 'stretch'

    - name: install zabbix deb in Debian 9
      apt: deb="/tmp/{{ debian9_file }}"
      when: ansible_distribution_release == 'stretch'

    - name: install zabbix-agent 4.4 Debian 9
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes
      when: ansible_distribution_release == 'stretch'

    ### Debian 10
    - name: download zabbix deb file for Debian 10
      get_url:
        url: "{{ debian10_link }}" 
        dest: "/tmp/{{ debian10_file }}"
      when: ansible_distribution_release == 'buster'

    - name: install zabbix deb in Debian 10
      apt: deb="/tmp/{{ debian10_file }}"
      when: ansible_distribution_release == 'buster'

    - name: install zabbix-agent 4.4 Debian 10
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes
      when: ansible_distribution_release == 'buster'

    ##### enabled zabbix-agent
    - name: enable service zabbix-agent and ensure it is not masked
      systemd:
        name: zabbix-agent
        enabled: yes
        masked: no
      become: yes

    ##### check zabbix home dir and shell
    - name: Make sure a service is stopped
      systemd: state=stopped name=zabbix-agent
      become: yes

    - name: check zabbix home dir and shell
      user:
        name: zabbix
        shell: /bin/bash
        home: /etc/zabbix
      become: yes

    ##### mkdir /etc/zabbix/scripts and rights
    - name: mkdir /etc/zabbix/scripts and rights
      file:
        path: /etc/zabbix/scripts
        state: directory
        owner: zabbix
        group: zabbix
        mode: 0700
      become: yes

    ##### change zabbix_agentd.conf
    - name: change zabbix_agentd.conf Hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: 'Hostname=Zabbix server'
        line: "Hostname={{ ansible_hostname }}"
      become: yes
        
    - name: change zabbix_agentd.conf ServerActive
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: 'ServerActive=127.0.0.1'
        line: "ServerActive={{ zbx_srv }}"
      become: yes

    - name: change zabbix_agentd.conf Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: 'Server=127.0.0.1'
        line: "Server={{ zbx_srv }}"
      become: yes

    - name: change zabbix_agentd.conf EnableRemoteCommands
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: '# EnableRemoteCommands=0'
        line: 'EnableRemoteCommands=1'
      become: yes

    - name: change zabbix_agentd.conf LogRemoteCommands
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        state: present
        regexp: '# LogRemoteCommands=0'
        line: 'LogRemoteCommands=1'

    ##### Install Vulners plugin
    ### Debian
    - name: download plugin deb file for Debian
      get_url:
        url: https://repo.vulners.com/debian/vulners-repo.deb
        dest: /tmp/vulners-repo.deb
      when: ansible_os_family == "Debian"

    - name: install plugin deb in Debian
      apt: deb="/tmp/vulners-repo.deb"
      when: ansible_os_family == "Debian"

    - name: install plugin Debian
      apt:
        name: zabbix-threat-control-host
        update_cache: yes
      when: ansible_os_family == "Debian"

    ### Starting zabbix-agent
    - name: Make sure a service is started
      systemd: state=started name=zabbix-agent
      become: yes